# Generated by Django 4.1.3 on 2023-04-05 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('birth_date', models.DateField(default='1990-01-01')),
            ],
        ),
    ]
