# Generated by Django 4.1.3 on 2023-03-30 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_people', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='People',
            new_name='Person',
        ),
    ]
